
image: "yglukhov/nim-base"

before_script:
- nim -v

pages:
  stage: deploy
  script:
  - mkdir docs
  - nimble docs
  - cp metaevents.html docs/index.html
  artifacts:
    paths:
    - docs
  only:
  - master

test:nimble:
  stage: test
  script:
  - nimble -v
  - nimble tests